# ANDA-NI Virtual Neuroinformatics Course
# Neo: Representing Electrophysiology Data in Python

<img src="resources/D1S4/neo_logo.png" alt="Neo Logo" width="800"/>

|||
|--:|---|
|Homepage|[http://neuralensemble.org/neo](http://neuralensemble.org/neo)  |
|GitHub|[https://github.com/NeuralEnsemble/python-neo](https://github.com/NeuralEnsemble/python-neo)|
|Documentation|[https://neo.readthedocs.io/en/stable/](https://neo.readthedocs.io/en/stable/)|
|Bug reports|[https://github.com/NeuralEnsemble/python-neo/issues](https://github.com/NeuralEnsemble/python-neo/issues) |
|Python Package Index (PyPI)|[https://pypi.org/project/neo/](https://pypi.org/project/neo/) |

Welcome to the tutorial on using the `neo` library for representing electrophysiological data in Python in a standardized format.

## What is Neo?

Neo is a Python library to represent neurophysiological data stemming from heterogeneous sources. It aims to provide a standardized way work on such data with the idea that tools, such as analysis libraries, can accept Neo as a common data representation as input. In addition, Neo simplifies the interaction with proprietary data file formats.

**Key Features:**
- **Vast file format support:** Neo reads from many open and proprietory file formats and organizes data in a common data representation. 
- **Streamlined data objects:** Neo data objects are optimized to be generic to capture almost any experiment, yet capture all the required aspects of a piece of data.
- **Proxy Objects:** Growing file format support for on-demand reading of data from disk to support large files.  

## Why Use Neo?

Neo allows to simplify reading data from a large variety of file formats. Moreover, Neo structures give users the flexibility to forge data in a representation optimal for their needs, while retaining all important information about individual data assets.
 
- **Data Models:** Neo defines common data modalities in a fully self-describing way, including physical units and relationships between individual signals.
- **Metadata aware:** Individual Neo objects can be annotated with metadata, thus ensuring that data stays meaningful and connected to the experiment during the analysis process, supporting literate programming.
- **Interoperability:** By adhering to Neo data representations, it becomes easy to incorporate other tools based on the same standard, giving more flexibility and less errors in data conversion.

## Who is This Tutorial For?

This tutorial is designed for:
- **Researchers** who need to store experimental data in a structured and accessible manner.
- **Data Scientists** looking for standardized ways to manage complex data sets and metadata.
- **Software Developers** who are building applications that involve scientific data management and need a reliable file format.

## Prerequisites

Before starting this tutorial, it is recommended that you have:
- Basic understanding of scientific research data.
- Familiarity with concepts of data organization and metadata.
- Basic programming knowledge, preferably in Python.

In this tutorial, we will cover the fundamental aspects of the Neo (and quantities) library. By the end, you should be able to efficiently store, manage, and share your scientific data using Neo. Let's dive in!

##  Preparing to use Neo
- Standardized representation of ephys data during runtime with `neo`
- Efficient handling of large data arrays thanks to `numpy`
- Support for physical units and automatic unit conversion with `quantities`

In [8]:
import neo
import numpy as np
import quantities as pq
import os.path

<img src="resources/D1S4/neo_as_interface.svg" width="1600"/>

## Data loading - input/output (IO)
The first step of any processing or analysis is to load the dataset. Neo provides a simple API to load various files from different sources.

**Given a file or a directory** : use `neo.io` to load the dataset and generate the Neo representation during runtime
  * easy when dataset is simple (one raw file)
  * flexible when a dataset is complex (several devices, signals, images, triggers, trials, ...)

The data for this session is contained in 'data'. In order to select the proper `neo.io`, we check the files:

In [9]:
!ls data

'ls' is not recognized as an internal or external command,
operable program or batch file.


Neo comes with a long list of available IOs for different file formats commonly used in ephys.
The full list can be obtained with:

In [10]:
neo.iolist

[neo.io.alphaomegaio.AlphaOmegaIO,
 neo.io.asciiimageio.AsciiImageIO,
 neo.io.asciisignalio.AsciiSignalIO,
 neo.io.asciispiketrainio.AsciiSpikeTrainIO,
 neo.io.axographio.AxographIO,
 neo.io.axonaio.AxonaIO,
 neo.io.axonio.AxonIO,
 neo.io.bci2000io.BCI2000IO,
 neo.io.biocamio.BiocamIO,
 neo.io.blackrockio.BlackrockIO,
 neo.io.blkio.BlkIO,
 neo.io.brainvisionio.BrainVisionIO,
 neo.io.brainwaredamio.BrainwareDamIO,
 neo.io.brainwaref32io.BrainwareF32IO,
 neo.io.brainwaresrcio.BrainwareSrcIO,
 neo.io.cedio.CedIO,
 neo.io.edfio.EDFIO,
 neo.io.elanio.ElanIO,
 neo.io.elphyio.ElphyIO,
 neo.io.exampleio.ExampleIO,
 neo.io.igorproio.IgorIO,
 neo.io.intanio.IntanIO,
 neo.io.klustakwikio.KlustaKwikIO,
 neo.io.kwikio.KwikIO,
 neo.io.mearecio.MEArecIO,
 neo.io.maxwellio.MaxwellIO,
 neo.io.medio.MedIO,
 neo.io.micromedio.MicromedIO,
 neo.io.nixio.NixIO,
 neo.io.nixio_fr.NixIO,
 neo.io.neomatlabio.NeoMatlabIO,
 neo.io.nestio.NestIO,
 neo.io.neuralynxio.NeuralynxIO,
 neo.io.neuroexplorerio.NeuroExplor

In [11]:
neo.io_by_extension

{'lsx': [neo.io.alphaomegaio.AlphaOmegaIO],
 'mpx': [neo.io.alphaomegaio.AlphaOmegaIO],
 'txt': [neo.io.asciisignalio.AsciiSignalIO,
  neo.io.asciispiketrainio.AsciiSpikeTrainIO,
  neo.io.openephysbinaryio.OpenEphysBinaryIO,
  neo.io.tdtio.TdtIO],
 'asc': [neo.io.asciisignalio.AsciiSignalIO],
 'csv': [neo.io.asciisignalio.AsciiSignalIO],
 'tsv': [neo.io.asciisignalio.AsciiSignalIO, neo.io.phyio.PhyIO],
 'axgd': [neo.io.axographio.AxographIO, neo.io.stimfitio.StimfitIO],
 'axgx': [neo.io.axographio.AxographIO, neo.io.stimfitio.StimfitIO],
 '': [neo.io.axographio.AxographIO],
 'bin': [neo.io.axonaio.AxonaIO,
  neo.io.rawbinarysignalio.RawBinarySignalIO,
  neo.io.spikeglxio.SpikeGLXIO],
 'set': [neo.io.axonaio.AxonaIO],
 '1': [neo.io.axonaio.AxonaIO],
 '2': [neo.io.axonaio.AxonaIO],
 '3': [neo.io.axonaio.AxonaIO],
 '4': [neo.io.axonaio.AxonaIO],
 '5': [neo.io.axonaio.AxonaIO],
 '6': [neo.io.axonaio.AxonaIO],
 '7': [neo.io.axonaio.AxonaIO],
 '8': [neo.io.axonaio.AxonaIO],
 '9': [neo.io.axo

<img src="resources/D1S4/IODiagram.svg" width="1000"/>

With Neo IOs, one class  = one file format, e.g., axon, neuroexplorer, plexon, rawbinarysignal, blackrock, neuralynx, neuroscope, nest, openephy, intan, spikeglx, **nix**, ...

In this case we have `.nix`-files, so we use the `neo.io.NixIO`-class to load the dataset.

In [12]:
with neo.io.NixIO(os.path.join('resources', 'D1S4', 'l101210-001_small_cut_60.0s.nix'), 'ro') as io:  # 'ro': read only
    block = io.read_block()

We obtain a `neo.Block` object containing the data from the .nix-file. The structure of this block is built according to the Neo data model, of which the `neo.Block` constitutes the top level object that "contains everything". In the next section, we will investigate other parts of the Neo data model.

All Neo IOs generate a representation of the dataset using this model. For this reason, Neo reduces working with different file formats to working with a standardized representation of electrophysiology data during runtime.

## Neo data model: data, metadata and relationships
With Neo the following **concepts** can be modelled with Neo objects:

- data
- relationships

### Representing time series data

- `AnalogSignal`: Continuous data sampled in **regular** intervals
- `IrregularlySampledSignal`: Continuous data sampled in **irregular** intervals
- `ImageSequence`: Continuous 2D **image frames** sampled in regular intervals

![ImageSequence](resources/D1S4/base_schematic_2.svg)

`AnalogSignal`: Continuous data sampled in **regular** intervals

*essential metadata*: physical unit of samples, time stamps of the samples (first timestamp & sampling interval)

In [13]:
anasig = neo.AnalogSignal(np.random.random((50,2)), units='uV',
                          sampling_rate=10000*pq.Hz,
                          t_start=120*pq.ms)
anasig

AnalogSignal with 2 channels of length 50; units uV; datatype float64
sampling rate: 10000.0 Hz
time: 120.0 ms to 125.0 ms

Note the dimensions of `AnalogSignal` object: (`time`, `channel`). Naturally, this assumes all channels to be of the same length. Otherwise, one may use multiple `AnalogSignal` objects.

Neo objects are -- in essence -- numpy objects + quantities (for physical units) + extra information.

In [14]:
print(anasig.times)

[120.  120.1 120.2 120.3 120.4 120.5 120.6 120.7 120.8 120.9 121.  121.1
 121.2 121.3 121.4 121.5 121.6 121.7 121.8 121.9 122.  122.1 122.2 122.3
 122.4 122.5 122.6 122.7 122.8 122.9 123.  123.1 123.2 123.3 123.4 123.5
 123.6 123.7 123.8 123.9 124.  124.1 124.2 124.3 124.4 124.5 124.6 124.7
 124.8 124.9] ms


**Unit support**

Neo handles units and conversion automatically with ´quantities´

In [15]:
sig1 = neo.AnalogSignal([[1, 2, 3]],
                        units='uV',
                        sampling_rate=1000.*pq.Hz)
sig2 = neo.AnalogSignal([[1, 2, 3]],
                        units='mV',
                        sampling_rate=1000.*pq.Hz)
print(sig1+sig2)

[[1001. 2002. 3003.]] uV


### Representing spike data

- `SpikeTrain`: Spike time data (& optional waveform snippet)


![SpikeTrain](resources/D1S4/base_schematic_3.svg)

`SpikeTrain`: Spike time data (& optional waveform snippet)

*essential metadata* time values, physical units of times, (& waveform sampling rate, waveform offset to corresponding time value)

In [16]:
st = neo.SpikeTrain([1, 4, 5.7],
                    units='ms',
                    name='#001',
                    t_start=0*pq.ms,
                    t_stop=300*pq.ms)
print(f'spiketrain: {st}')
print(f't_start & t_stop: {st.t_start, st.t_stop}')

spiketrain: [1.  4.  5.7] ms
t_start & t_stop: (array(0.) * ms, array(300.) * ms)


### Representing experimental events
- `Event`: Experiment reference time points (e.g. trigger, trial start, ...)
- `Epoch`: Experiment reference time ranges (e.g. trial, stimulation, ...)

![Epoch](resources/D1S4/base_schematic_5.svg)

`Epoch`: Experiment reference time ranges (e.g. trial, stimulation, ...)

*essential metadata* time and dureation values, physical units of times, labels

In [17]:
ep = neo.Epoch(times=[3, 9, 15, 21],
               durations=[1, 1, 1, 1],
               units='ms',
               labels=["Start", "Wait", "Go", "Reward"])
print(f'epoch: {ep}')
print(f'epoch endpoints: {ep+ep.durations}')

epoch: [ 3  9 15 21] ms
epoch endpoints: [ 4 10 16 22] ms


### Representing relationships
- `Block`: contains all objects of a recording
- `Segment`: contains data objects with a shared clock, e.g. a trial
- `ChannelView`: select a **subset of channels** of a signal, e.g. all even channels of an `AnalogSignal`
- `Group`: groups data objects logically (no common clock required, e.g. `SpikeTrain`s of a neuronal unit)

### Overview and Hierarchical Overview

The following figure displays the Neo data model scheme.

![Structure](resources/D1S4/base_schematic.svg)

The Neo tree represents the hierarchical structure of the different parts.

```
Block 0
    .segments
        Segment 0
            .analogsignals
                AnalogSignal 0
                AnalogSignal 1
            .spiketrains
                SpikeTrain 0
                SpikeTrain 1
                SpikeTrain 2
        Segment 1
            .analogsignals
                AnalogSignal 0
                AnalogSignal 1
            .spiketrains
                SpikeTrain 0
                SpikeTrain 1
                SpikeTrain 2
Block 1
    .segments
        Segment 0
    ...
```

### Data annotation

#### Built-in object metadata attributes

- Object specific metadata: t_start, sampling_rate, ...
- Human readable labels of objects via `name` and `description` attributes
- `Event` and `Epoch` can be used to `label` each time point / time period

In [18]:
ep.name = "Experiment times"
ep.description = "These epochs contain all experimental periods"

#### Annotations
Give a custom annotation, i.e., key-value pair of metadata, for any Neo object.

In [19]:
sig = neo.AnalogSignal(
    np.random.randn(50, 8), units='uV', sampling_rate=1000.*pq.Hz)
sig.annotate(quality='excellent')
print(sig.annotations)
print('shape:', sig.shape)

{'quality': 'excellent'}
shape: (50, 8)


#### Array annotations
Use array annotations to custom label each individual piece of data in an object, i.e., each channel of an `AnalogSignal`, each event of an `Event` object, each spike in a `SpikeTrain` object.

In [20]:
sig.array_annotate(
    electrode_id=[1, 2, 3, 4, 21, 22, 23, 24],
    tetrode_group=['A','A','A','A', 'B', 'B', 'B', 'B' ])
print(sig.array_annotations)

{'electrode_id': array([ 1,  2,  3,  4, 21, 22, 23, 24]), 'tetrode_group': array(['A', 'A', 'A', 'A', 'B', 'B', 'B', 'B'], dtype='<U1')}


Array annotations are useful, in particular, to subselect data from a Neo object.

In [21]:
group_B, = np.nonzero(sig.array_annotations['tetrode_group']=='B')
print(group_B)
sig_group_B = sig[:, group_B]
print('shape:', sig_group_B.shape)
print(sig_group_B.array_annotations)

[4 5 6 7]
shape: (50, 4)
{'electrode_id': array([21, 22, 23, 24]), 'tetrode_group': array(['B', 'B', 'B', 'B'], dtype='<U1')}


## Dataset overview

### General block-level overview
We can directly get an overview of the contained objects from the `neo.Block` print

In [35]:
block

Block with [<neo.core.segment.Segment object at 0x000002208F10B9B0>] segments, [<neo.core.group.Group object at 0x000002208F94D160>] groups
name: 'Reachgrasp Recording Data Block'
description: 'Block of reach-to-grasp project data from Blackrock file set.'
annotations: {'nix_name': 'neo.block.672f43da228e44b2a3c49724a10672f8',
  'avail_file_set': ['ns2', 'ns5', 'nev'],
  'avail_nsx': [2, 5],
  'avail_nev': True,
  'rec_pauses': False,
  'conditions': 1,
  'project_name': 'reach-to-grasp',
  'project_type': 'electrophysiology',
  'project_subtype': 'motor behavior',
  'taskdesigns': 'TwoCues',
  'subject_name': 'monkey_L',
  'subject_gender': 'female',
  'subject_activehand': 'left',
  'subject_birthday': '[datetime.date(2004, 3, 19)]',
  'setup_location': 'Inst. de Neurosciences Cognitives de la Mediterranee (INCM), GLM, CNRS - Aix Marseille Univ., Marseille, France',
  'array_serialnum': '1025-0503',
  'connector_type': 'CerePort',
  'arraygrids_tot_num': 1,
  'electrodes_tot_num': 10

This summary already tells us that we only need to take care of a single segment with three event objects, two analogsignals and multiple spiketrain objects. The 96 continuously sampled channels of the second analogsignal are sampled a 'low' sampling rate of 1kHz and contain neural data, so data comparable to local-field potential measurements.

### Dataset overview - SpikeTrains
To learn more about the spiketrains, we print the spiketrain annotations:

In [27]:
segment = block.segments[0]
segment.spiketrains[2].annotations

{'nix_name': 'neo.spiketrain.f07b90715c434e46a2e6ad8f282e79dd',
 'id': 'Unit 2000',
 'channel_id': 2,
 'unit_id': 0,
 'unit_tag': 'unclassified',
 'electrode_reject_HFC': False,
 'electrode_reject_LFC': False,
 'electrode_reject_IFC': True,
 'connector_aligned_id': 92,
 'coordinate_x': array(0.4) * mm,
 'coordinate_y': array(3.6) * mm,
 'sua': False,
 'mua': False,
 'noise': True}

In [29]:
segment.spiketrains[0]

SpikeTrain containing 4192 spikes with waveforms; units s; datatype float64 
name: 'ch1#0'
description: 'SpikeTrain channel_id: 1, unit_id: 0'
annotations: {'nix_name': 'neo.spiketrain.97c483b9aed942b39abfa2abc1c84921',
  'id': 'Unit 1000',
  'channel_id': 1,
  'unit_id': 0,
  'unit_tag': 'unclassified',
  'electrode_reject_HFC': False,
  'electrode_reject_LFC': False,
  'electrode_reject_IFC': False,
  'connector_aligned_id': 91,
  'coordinate_x': array(0.) * mm,
  'coordinate_y': array(3.6) * mm,
  'sua': False,
  'mua': False,
  'noise': True}
time: 0.0 s to 60.0 s

We see that in this example, spiketrains are annotated with a 'connector_aligned_id', indicating the spatial source of the signal. In addition the coordinates in x and y direction are provided in physical units for each channel and spiketrain. Spiketrains also carry information about 'noise', 'mua' or 'sua' assignment, indicating that the spikes were spikesorted and assigned to one of the three unit categories:
- *noise*: non-neural threshold crossing events)
- *mua*: multi-unit-activity - neural threshold crossing events not uniquely assigned to a putative neuron
- *sua*: single-unit-activity - neural threshold crossing events assigned to a single virtual neuron
Note that all of these annotations are custom annotations given by the experimenter to facilitate working with the data.

### Dataset overview - AnalogSignals
To learn more about the channels of the `AnalogSignal`, we print the entries of the array_annotations of the single analogsignal object:

In [30]:
print(segment.analogsignals[0].array_annotations.keys())
print(segment.analogsignals[1].array_annotations.keys())

dict_keys(['channel_names', 'channel_ids'])
dict_keys(['channel_names', 'channel_ids', 'hi_pass_freq', 'lo_pass_freq', 'hi_pass_order', 'lo_pass_order', 'filter_type', 'electrode_reject_HFC', 'electrode_reject_LFC', 'electrode_reject_IFC', 'connector_aligned_ids', 'coordinates_x', 'coordinates_y'])


In [31]:
print(segment.analogsignals[0].name)
print(segment.analogsignals[0].array_annotations['channel_names'])

nsx2
['ainp9' 'ainp10' 'ainp11' 'ainp12' 'ainp13' 'ainp15']


In [32]:
print(segment.analogsignals[1].name)
print(segment.analogsignals[1].array_annotations['channel_names'])

LFP (offline filtered ns5)
['chan1' 'chan2' 'chan3' 'chan4' 'chan5' 'chan6' 'chan7' 'chan8' 'chan9'
 'chan10' 'chan11' 'chan12' 'chan13' 'chan14' 'chan15' 'chan16' 'chan17'
 'chan18' 'chan19' 'chan20' 'chan21' 'chan22' 'chan23' 'chan24' 'chan25'
 'chan26' 'chan27' 'chan28' 'chan29' 'chan30' 'chan31' 'chan32' 'chan33'
 'chan34' 'chan35' 'chan36' 'chan37' 'chan38' 'chan39' 'chan40' 'chan41'
 'chan42' 'chan43' 'chan44' 'chan45' 'chan46' 'chan47' 'chan48' 'chan49'
 'chan50' 'chan51' 'chan52' 'chan53' 'chan54' 'chan55' 'chan56' 'chan57'
 'chan58' 'chan59' 'chan60' 'chan61' 'chan62' 'chan63' 'chan64' 'chan65'
 'chan66' 'chan67' 'chan68' 'chan69' 'chan70' 'chan71' 'chan72' 'chan73'
 'chan74' 'chan75' 'chan76' 'chan77' 'chan78' 'chan79' 'chan80' 'chan81'
 'chan82' 'chan83' 'chan84' 'chan85' 'chan86' 'chan87' 'chan88' 'chan89'
 'chan90' 'chan91' 'chan92' 'chan93' 'chan94' 'chan95' 'chan96']


### Dataset overview - Events
To learn more about the events, we print the labels and annotations of a single event object:

In [33]:
import numpy as np
event = segment.events[2]
print(f'Event object name: {event.name}')
print(f'Number of event times: {len(event)}')
print(f'Unique event labels: {np.unique(event.labels)}')
print(f'Event annotation keys: {event.array_annotations.keys()}')
print(f'Unique trial_ids: {np.unique(event.array_annotations["trial_id"])}')
print(f'Number of reward-on events: {sum(event.labels=="RW-ON")}')

Event object name: TrialEvents
Number of event times: 256
Unique event labels: ['CUE-OFF' 'CUE-ON' 'DO' 'ERROR-FLASH-OFF' 'ERROR-FLASH-ON' 'FSRplat-OFF'
 'FSRplat-ON' 'GO-ON' 'GO/RW-OFF' 'HEplat-OFF' 'HEplat-ON' 'NONE' 'OBB'
 'OR' 'OT' 'RW-ON' 'RW-ON-REP' 'SR' 'SR-REP' 'STOP' 'TS-OFF' 'TS-ON'
 'WS-ON']
Event annotation keys: dict_keys(['trial_id', 'trial_timestamp_id', 'performance_in_trial', 'performance_in_trial_str', 'belongs_to_trialtype', 'trial_event_labels', 'trial_reject_HFC', 'trial_reject_LFC', 'trial_reject_IFC'])
Unique trial_ids: [-1  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
Number of reward-on events: 11


## Dealing with large datasets and Proxy objects
How to load only required data

- some IOs are based on `RawIO` concept for efficient reading of data
- `RawIO`s require additional symmetries in the dataset for efficient loading
- *lazy* data objects (ProxyObjects) can be loaded using `io.read_block(`**`lazy=True`**`)`
- ProxyObjects provide a `.load(t_start, t_stop)` method that loads requested data in memory and returns complete neo data object.

In [34]:
io = neo.io.NixIOFr(os.path.join('resources', 'D1S4', 'l101210-001_small_cut_60.0s.nix'))
lazy_block = io.read_block(lazy=True)

In [22]:
lazy_anasig = lazy_block.segments[0].analogsignals[1]

ProxyObjects contain metadata and shape information

In [23]:
print(f'signal duration: {lazy_anasig.t_start} -  {lazy_anasig.t_stop}')
print(f'signal shape: {lazy_anasig.shape}')
print(f'signal sampling rate: {lazy_anasig.sampling_rate}')
print(f'signal annotations: {lazy_anasig.annotations}')

signal duration: 0.0 s -  60.0 s
signal shape: (60000, 96)
signal sampling rate: 1000.0 Hz
signal annotations: {'stream_id': '5', 'nsx': 5, 'neural_signal': True, 'filter_shift_correction': 0.0, 'nix_name': 'neo.analogsignal.7d51aeb30d2b4a2f912a583214cf8bea'}


Data of a specific channel and time range can be loaded selectively into a new neo object

In [24]:
real_lazy_anasig = lazy_anasig.load(time_slice=(0.5*pq.s,0.6*pq.s), channel_indexes=[0])

In [25]:
print(f'signal duration: {lazy_anasig.t_start} -  {lazy_anasig.t_stop}')
print(f'signal shape: {real_lazy_anasig.shape}')
print(f'signal sampling rate: {real_lazy_anasig.sampling_rate}')
print(f'signal annotations: {real_lazy_anasig.times}')
print(f'signal values: {real_lazy_anasig.magnitude}')

signal duration: 0.0 s -  60.0 s
signal shape: (100, 1)
signal sampling rate: 1000.0 Hz
signal annotations: [0.5   0.501 0.502 0.503 0.504 0.505 0.506 0.507 0.508 0.509 0.51  0.511
 0.512 0.513 0.514 0.515 0.516 0.517 0.518 0.519 0.52  0.521 0.522 0.523
 0.524 0.525 0.526 0.527 0.528 0.529 0.53  0.531 0.532 0.533 0.534 0.535
 0.536 0.537 0.538 0.539 0.54  0.541 0.542 0.543 0.544 0.545 0.546 0.547
 0.548 0.549 0.55  0.551 0.552 0.553 0.554 0.555 0.556 0.557 0.558 0.559
 0.56  0.561 0.562 0.563 0.564 0.565 0.566 0.567 0.568 0.569 0.57  0.571
 0.572 0.573 0.574 0.575 0.576 0.577 0.578 0.579 0.58  0.581 0.582 0.583
 0.584 0.585 0.586 0.587 0.588 0.589 0.59  0.591 0.592 0.593 0.594 0.595
 0.596 0.597 0.598 0.599] s
signal values: [[ 62.45171877]
 [ 63.93707171]
 [ 62.65709229]
 [ 63.07354262]
 [ 64.39311159]
 [ 61.53823878]
 [ 53.72240943]
 [ 46.86402527]
 [ 43.03524546]
 [ 37.10747356]
 [ 28.20011349]
 [ 19.54728144]
 [  9.53482583]
 [ -1.77291963]
 [-10.43101018]
 [-15.08679717]
 [-15.353

## Ways to save data in Neo
- selected open formats are supported for writing
 - **NIX**<sup>1</sup>
 - NWB<sup>1</sup>
 - Matlab<sup>2</sup>
 - Ascii<sup>2</sup>
 - Numpy Pickle<sup>3</sup>

1. Support of neo-compatible files
2. Does not capture complete set of metadata
3. Strong dependency on Numpy and Neo version

In [26]:
filename = 'my_first_neo_dataset.nix'
with neo.io.NixIO(filename, 'ow') as io:
    io.write_block(block)

## Working with a dataset - Neo methods and utility functions

In the following lines we are going to introduce a set of useful features of Neo objects while cutting the dataset into individual trial segments. Based on the trial events and their annotations we can identify successful (correct) trials and select the time around the start of the trial.

### Filter: select an object in a neo structure

We can get a list of objects in a Neo tree with:

  * Segment.filter(...)
  * Block.filter(...)

The filtering can be done on the object type, on attributes or on annoations or everything combined.

Example:
```python
obj.filter(name="Vm")
obj.filter(objects=neo.SpikeTrain)
obj.filter(targdict={'myannotation':3})
```

Lets go back to the dataset we loaded and get a list of Spiketrains annotated without noise.

In [27]:
sts = block.filter(
    objects=neo.SpikeTrain, targdict={'noise': False})
type(sts)

neo.core.spiketrainlist.SpikeTrainList

In [28]:
print(sts[0].annotations['noise'])

False


### Masking Neo objects

First we are selecting event times that are occurring during successful trials, marked by the `performance_in_trial_str` as `correct_trial`. In addition we also only want to select trial start (`TS-ON`) events. Based on the array annotations we are creating two masks and apply both to the original event to generate a new event object via slicing.

In [29]:
mask1 = event.array_annotations['performance_in_trial_str'] == 'correct_trial'
mask2 = event.array_annotations['trial_event_labels'] == 'TS-ON'
correct_TS_event = event[mask1 & mask2]
print(len(correct_TS_event))

12


In [30]:
start_event = correct_TS_event

### Utility function: Epoch creation
In the next step we are making use of neo utility functions to generate epochs around the time points extracted.

Construct analysis epochs from 10ms before the TS-ON of a successful behavioral trial to 15ms after TS-ON. The name "analysis_epochs" is given to the resulting Neo Epoch object. The object is not attached to the Neo Segment. The parameter event2 of add_epoch() is left empty, since we are cutting around a single event, as opposed to cutting between two events.

In [31]:
from neo.utils import add_epoch

In [32]:
pre = -1 * pq.ms
post = 15 * pq.ms
epoch = add_epoch(
    segment,
    event1=start_event, event2=None,
    pre=pre, post=post,
    attach_result=False,
    name='analysis_epochs')

The number of epochs generated is the same as the number of trial start events and all epochs have the same duration as we extract 25ms of data around each trial start event.

In [33]:
print('Number of epochs: {}'.format(len(epoch)))
print('Durations of epochs: {}'.format(epoch.durations))

Number of epochs: 12
Durations of epochs: [0.016 0.016 0.016 0.016 0.016 0.016 0.016 0.016 0.016 0.016 0.016 0.016] s


### Utility function: cutting segment by epochs


Now we use the previously defined epochs to cut the segment containing the complete dataset into subsets, where each new segment corresponds to the starting epoch of a successful trial. For capturing the newly generated segments, we create a new Neo block.

Create new segments of data cut according to the analysis epochs of the 'analysis_epochs' Neo Epoch object. The time axes of all segments are aligned such that each segment starts at time 0 (parameter reset_times); annotations describing the analysis epoch are carried over to the segments. A new Neo Block named "data_cut_to_analysis_epochs" is created to capture all cut analysis epochs.


In [34]:
from neo.utils import cut_segment_by_epoch

cut_trial_block = neo.Block(name="data_cut_to_analysis_epochs")
cut_trial_block.segments = cut_segment_by_epoch(segment, epoch, reset_time=True)

In [35]:
len(cut_trial_block.segments)

12

We can confirm that the resetting of the times during the segmentation process was successfull by checking the new times of the trial start events in the new segments:

In [36]:
print('In the new trial TS is happening at {}'.format([s.events[-1][0] for s in cut_trial_block.segments]))

In the new trial TS is happening at [array(0.001) * s, array(0.001) * s, array(0.001) * s, array(0.001) * s, array(0.001) * s, array(0.001) * s, array(0.001) * s, array(0.001) * s, array(0.001) * s, array(0.001) * s, array(0.001) * s, array(0.001) * s]


### More interesting features
- *`DataObject`*`.time_slice()` - create a new object containing data in a subset of the original time span -- works also for containers!
- *`DataObject`*`.time_shift()` - create a new object containing data shifted in time
- *`DataObject`*`.merge()` - merge data values of two DataObjects
- *`DataObject`*`.concatenate()` - concatenate data values of two DataObjects
- `AnalogSignal.downsample()` - create an AnalogSignal with a lower sampling rate
- *`Object`*`.parents`, e.g. `AnalogSignal.segment` - to navigate up in neo object structure
- *`Quantity`*`.rescale()` - rescale the data to a new physical unit, e.g., `.rescale(pq.ms)` to rescale to milliseconds
- *`Quantity`*`.magnitude` - strip units and return a plain numpy array
- *`Quantity`*`.simplified()` - simplifies units to SI units
- *`Quantity`*`.dimensionality.latex` - get latex representation of physical unit (for plotting)


In [37]:
anasig

AnalogSignal with 2 channels of length 50; units uV; datatype float64
sampling rate: 10000.0 Hz
time: 120.0 ms to 125.0 ms

In [38]:
anasig.time_slice(121*pq.ms,123*pq.ms)

AnalogSignal with 2 channels of length 20; units uV; datatype float64
sampling rate: 10000.0 Hz
time: 121.0 ms to 123.0 ms

In [39]:
anasig.time_shift(.300*pq.s)

AnalogSignal with 2 channels of length 50; units uV; datatype float64
sampling rate: 10000.0 Hz
time: 420.0 ms to 425.0 ms

In [40]:
anasig.downsample(3)

AnalogSignal with 2 channels of length 17; units uV; datatype float64
sampling rate: 3333.3333333333335 Hz
time: 120.0 ms to 125.1 ms

In [41]:
anasig.merge(anasig)

AnalogSignal with 4 channels of length 50; units uV; datatype float64
sampling rate: 10000.0 Hz
time: 120.0 ms to 125.0 ms

In [42]:
anasig.concatenate(anasig.time_shift(5*pq.ms))

AnalogSignal with 2 channels of length 100; units uV; datatype float64
annotations: {'annotations': {}}
sampling rate: 10000.0 Hz
time: 120.0 ms to 130.0 ms

In [43]:
print(anasig[0:10])

[[0.98800254 0.12441614]
 [0.65779574 0.37835699]
 [0.82705554 0.31226656]
 [0.75502174 0.09170331]
 [0.92974077 0.03085436]
 [0.52828176 0.76641894]
 [0.932304   0.23667711]
 [0.73583899 0.79314053]
 [0.24690638 0.36779236]
 [0.37770457 0.90469682]] uV


In [44]:
print(anasig[0:100].dimensionality)

uV


In [45]:
print(anasig[0:10].rescale(pq.V))

[[9.88002536e-07 1.24416135e-07]
 [6.57795744e-07 3.78356992e-07]
 [8.27055541e-07 3.12266561e-07]
 [7.55021744e-07 9.17033149e-08]
 [9.29740773e-07 3.08543612e-08]
 [5.28281763e-07 7.66418937e-07]
 [9.32304003e-07 2.36677112e-07]
 [7.35838994e-07 7.93140528e-07]
 [2.46906380e-07 3.67792358e-07]
 [3.77704566e-07 9.04696817e-07]] V


In [46]:
print(anasig[0:10].times)

[120.  120.1 120.2 120.3 120.4 120.5 120.6 120.7 120.8 120.9] ms


In [47]:
print(anasig[0:10].times.rescale(pq.CompoundUnit("1/30000*s")))

[3600. 3603. 3606. 3609. 3612. 3615. 3618. 3621. 3624. 3627.] (1/30000*s)


In [48]:
print(anasig[0:10].magnitude)

[[0.98800254 0.12441614]
 [0.65779574 0.37835699]
 [0.82705554 0.31226656]
 [0.75502174 0.09170331]
 [0.92974077 0.03085436]
 [0.52828176 0.76641894]
 [0.932304   0.23667711]
 [0.73583899 0.79314053]
 [0.24690638 0.36779236]
 [0.37770457 0.90469682]]
